### ISSUE TITLE
Can't build image, because nix release url changed

### ISSUE THREAD

**Issue by Soulmeister-x** [redoracle/nixos#1]
while running `docker build .` the building fails at the `wget` step

The problem is probably that the resource location has changed.

The builds are now located at https://releases.nixos.org/?prefix=nix/

Also I don't see a "latest" link anymore, so maybe the latest version has to be parsed in the build script

[out.log](https://github.com/redoracle/nixos/files/12705251/out.log)

**Comment by redoracle** [comment]
Subject: Apologies for the Delay – NixOS Container Now Available

Dear Soulmeister-x,

I sincerely apologize for the very late reply and any inconvenience this may have caused. Thank you so much for bringing the issue to my attention regarding the build failure during the `wget` step. You're absolutely right—the resource location has changed, and there no longer appears to be a "latest" link available.

I'm happy to inform you that the Dockerfile has been updated to address this issue, and the container is now successfully published on both Docker Hub and GitHub Container Registry (GHCR):

- Docker Hub: [https://hub.docker.com/r/redoracle/nixos](https://hub.docker.com/r/redoracle/nixos)
- GHCR: [ghcr.io/redoracle/nixos](https://ghcr.io/redoracle/nixos)

Thank you again for your help and patience, and please don't hesitate to reach out if you encounter any further issues.

Best regards
